export const clubsArg = [
   "Aldosivi",
   "All Boys",
   "Argentinos Juniors",
   "Arsenal",
   "Atletico Tucumán",
   "Banfield",
   "Barracas Central",
   "Belgrano",
   "Boca",
   "Central de Cordoba",
   "Chacarita",
   "Colón",
   "Defensa y Justicia",
   "Estudiantes de la plata",
   "Ferro",
   "Gimnasia y Esgrima de la plata",
   "Godoy Cruz",
   "Huracan",
   "Independiente",
   "Instituto",
   "Lanus",
   "Newells",
   "Patronato",
   "Platense",
   "Racing",
   "River",
   "Rosario Central",
   "San Lorenzo",
   "Sarmiento",
   "Talleres",
   "Temperley",
   "Tigre",
   "Union",
   "Velez",
]
